version: '3.8'
services:
  php:
    build:
      context: docker/php
      target: "base"
    volumes:
      - .:/var/www/delivery:delegated
    links:
      - mysql
  nginx:
    image: nginx:1.25
    ports:
      - "8020:80"
    volumes:
      - .:/var/www/delivery:delegated
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'delivery'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
